objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Establishment_Date__c</fullName>
        <description>This field should be entered by team members. This date is for when the business was first originally started.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Establishment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MembershipDate__c</fullName>
        <description>This is the date member was added to DNA</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrganizationNumber__c</fullName>
        <description>DNA org number for existing organizations</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Organization Number</label>
        <length>22</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationTaxID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Tax ID is the tax identification number for the organization.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <externalId>true</externalId>
        <label>Organization Tax ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonNumber__c</fullName>
        <description>justin added this to be able to upsert accounts before upserting contacts as we need to link them together</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Person Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VerifiedIdentityPhone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VerifiedIdentityPhone</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SFOrganization.cls
/**
 * Model object that encapsulates a SalesForce Account object
 */
public class SFOrganization implements IOrganization {
    private Account account;

    public SFOrganization(Account account) {
        this.account = account;
    }

    public Account getAccount() {
        return this.account;
    }

    public SFAddress getAddress() {
        return new SFAddress(this.account, AddressType.PRIMARY);
    }

    public String getEmailAddress() {
        return this.account != null ? this.account.Email__c : null;
    }

    public Date getMembershipDate() {
        return this.account != null ? this.account.MembershipDate__c : null;
    }

    public Date getBusinessEstablishmentDate() {
        return this.account != null ? this.account.Business_Establishment_Date__c : null;
    }

    public String getName() {
        return this.account != null ? this.account.Name : null;
    }

    public String getOrgNumber() {
        return this.account != null ? this.account.OrganizationNumber__c : null;
    }

    public String getOrgType() {
        return this.account != null ? this.account.OrganizationType__c : null;
    }

    public String getPhoneNumber() {
        return this.account != null ? this.account.Phone : null;
    }

    public IOrganization getRedactedOrganization() {
        return new RedactedOrganization(this);
    }

    public String getTaxId() {
        return this.account != null ? this.account.OrganizationTaxID__c : null;
    }

    public static SFOrganization getInstance(Id accountId) {
        if (accountId == null) {
            return new SFOrganization(null);
        }

        List<Account> accounts = [
            SELECT
                Email__c,
                Name,
                OrganizationNumber__c,
                OrganizationTaxID__c,
                OrganizationType__c,
                MembershipDate__c,
                Business_Establishment_Date__c,
                PersonNumber__c,
                Phone,
                BillingStreet,
                BillingCity,
                BillingState,
                BillingPostalCode,
                BillingCountry,
                VerifiedIdentityPhone__c

            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];

        if (accounts.size() == 0) {
            return new SFOrganization(null);
        }

        Account a = accounts[0];
        SFOrganization o = new SFOrganization(a);
        return o;
    }
}