objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>OrganizationNumber__c</fullName>
        <description>DNA org number for existing organizations</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Organization Number</label>
        <length>22</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationTaxID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Tax ID is the tax identification number for the organization.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <externalId>true</externalId>
        <label>Organization Tax ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SFOrganizationTest.cls
@isTest
private class SFOrganizationTest {

    @isTest
    private static void testHappyPath() {
        String email = 'email@example.com';
        String name = 'Name';
        String orgNumber = 'Org Number';
        String taxID  = '888-88-8888';
        String orgType = '1234';
        String phone = '555-555-5555';
        String street = '123 Main';
        String city = 'pocatello';
        String state = 'ID';
        String postalCode = '83201';
        String country = 'USA';

        Account testAccount = new Account (
            Email__c = email,
            Name =  name,
            OrganizationNumber__c = orgNumber,
            OrganizationTaxID__c = taxID,
            OrganizationType__c = orgType,
            Phone = phone,
            BillingStreet = street,
            BillingCity = city,
            BillingState = state,
            BillingPostalCode = postalCode,
            BillingCountry = country
        );

        SFOrganization account = new SFOrganization(testAccount);

        System.assertEquals(email, account.getEmailAddress());
        System.assertEquals(name, account.getName());
        System.assertEquals(orgNumber, account.getOrgNumber());
        System.assertEquals(orgType, account.getOrgType());
        System.assertEquals(phone, account.getPhoneNumber());
        System.assertEquals(taxID, account.getTaxId());
        System.assertEquals(street, account.getAddress().getStreet());
        System.assertEquals(city, account.getAddress().getCity());
        System.assertEquals(state, account.getAddress().getStateCode());
        System.assertEquals(postalCode, account.getAddress().getPostalCode());
        System.assertEquals(country, account.getAddress().getCountryCode());
    }
}