objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Establishment_Date__c</fullName>
        <description>This field should be entered by team members. This date is for when the business was first originally started.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Establishment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MembershipDate__c</fullName>
        <description>This is the date member was added to DNA</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Membership Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OrganizationNumber__c</fullName>
        <description>DNA org number for existing organizations</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Organization Number</label>
        <length>22</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationTaxID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The Tax ID is the tax identification number for the organization.</description>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <externalId>true</externalId>
        <label>Organization Tax ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Organization Type</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonNumber__c</fullName>
        <description>justin added this to be able to upsert accounts before upserting contacts as we need to link them together</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Person Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>DNA</fullName>
        <active>true</active>
        <label>DNA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DNAOrganization.cls
/**
 * Model object representing a DNA organization
 */
public class DNAOrganization implements IOrganization {
    private DNAAddress address;
    private String emailAddress;
    private String name;
    private String orgNumber;
    private String orgType;
    private String phoneNumber;
    private String taxId;

    public DNAOrganization(DNAAddress address, String emailAddress, String name, String orgNumber, String orgType, String phoneNumber, String taxId) {
        this.address = address;
        this.emailAddress = emailAddress;
        this.name = name;
        this.orgNumber = orgNumber;
        this.orgType = orgType;
        this.phoneNumber = phoneNumber;
        this.taxId = taxId;
    }

    public Account getAccount() {
        Account a = new Account();
        a.Email__c = this.emailAddress;
        a.MembershipDate__c = null;
        a.Business_Establishment_Date__c = null;
        a.Name = this.name;
        a.OrganizationNumber__c = this.orgNumber;
        a.OrganizationTaxID__c = this.taxId;
        a.OrganizationType__c = this.orgType;
        a.PersonNumber__c = null;
        a.Phone = this.phoneNumber;
        a.BillingStreet = this.address.getStreet();
        a.BillingCity = this.address.getCity();
        a.BillingState = this.address.getStateCode();
        a.BillingPostalCode = this.address.getPostalCode();
        a.BillingCountry = this.address.getCountryCode();

        return a;
    }

    public DNAAddress getAddress() {
        return this.address;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public Date getMembershipDate() {
        return null;
    }

    public Date getBusinessEstablishmentDate() {
        return null;
    }

    public String getName() {
        return this.name;
    }

    public String getOrgNumber() {
        return this.orgNumber;
    }

    public String getOrgType() {
        return this.orgType;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public IOrganization getRedactedOrganization() {
        return new RedactedOrganization(this);
    }

    public String getTaxId() {
        return this.taxId;
    }
}