objects/Account.object
<CustomObject>
    <fields>
        <fullName>MemberNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Member Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Org_Number__c</fullName>
        <description>DNA org number for existing organizations</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter org number leading with O. For example, O12345</inlineHelpText>
        <label>Org Number</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>OrganizationNumber__c</fullName>
        <description>DNA org number for existing organizations</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Organization Number</label>
        <length>22</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PersonNumber__c</fullName>
        <description>justin added this to be able to upsert accounts before upserting contacts as we need to link them together</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Person Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>DNA</fullName>
        <active>true</active>
        <label>DNA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IdentificationExpirationDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueState__c</fullName>
        <label>Identification Issue State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IdentificationNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IdentificationType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Type</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Member Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PersonNumber__c</fullName>
        <description>Number provided by DNA</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Person Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TaxID__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>DNA</fullName>
        <active>true</active>
        <description>Imported from DNA</description>
        <label>DNA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>IdentificationExpirationDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueState__c</fullName>
        <label>Identification Issue State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IdentificationNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IdentificationType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Type</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Member Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Person Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <externalId>true</externalId>
        <label>Tax ID</label>
        <length>60</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/MemberInsight__c.object
<CustomObject>
    <description>An object for user created insights on the member record page.</description>
    <fields>
        <fullName>ContactID__c</fullName>
        <description>Links the insight to a member</description>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Member Insights</relationshipLabel>
        <relationshipName>Member_Insights</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExtraDetails__c</fullName>
        <description>Any additional details the MCC agent determines is important and notable but is longer than the title</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Extra Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>InsightType__c</fullName>
        <description>Insight type is defined by the categories we determine are needed for insights</description>
        <label>Insight Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Declined</fullName>
                    <label>Declined (Phone Password, eBranch, etc.)</label>
                </value>
                <value>
                    <fullName>Fraud</fullName>
                </value>
                <value>
                    <fullName>Gender</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Military</fullName>
                </value>
                <value>
                    <fullName>Name Pronunciation</fullName>
                </value>
                <value>
                    <fullName>Touch Tone Teller</fullName>
                </value>
                <value>
                    <fullName>Declined Phone Password</fullName>
                    <isActive>false</isActive>
                    <label>Declined Phone Password</label>
                </value>
                <value>
                    <fullName>Fruad</fullName>
                    <isActive>false</isActive>
                    <label>Fruad</label>
                </value>
                <value>
                    <fullName>No Cross Sell</fullName>
                    <isActive>false</isActive>
                    <label>No Cross Sell</label>
                </value>
                <value>
                    <fullName>No Self Help</fullName>
                    <isActive>false</isActive>
                    <label>No Self Help</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Member Insight</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Member Insight Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Insights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>MemberNumber__c</fullName>
        <description>Used by data loads to automatically link to an account/contact.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Member Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <businessProcess>FSC Loan Process</businessProcess>
        <description>Loan products except HELOC</description>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {

    public static Account createAccount(Boolean isDna, Boolean doInsert) {
        List<Account> accounts = TestDataFactory.createAccounts(1, true, doInsert);
        return accounts[0];
    }

    public static List<Account> createAccounts(Integer numAccounts, Boolean isDna, Boolean doInsert) {
        String recordTypeName = isDna ? RecordTypeConstants.ACCOUNT_DNA : RecordTypeConstants.ACCOUNT_DEFAULT;
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        List<Account> accts = new List<Account>();
        for(Integer i = 0; i < numAccounts; i++) {
            String orgNumber = '' + 100 + i;
            String phone = '(234) 234-' + String.valueOf(i).leftPad(4, '0');
            Account a = new Account(
                industry = 'Energy',
                name = 'O' + orgNumber + ' - Test Company ' + i,
                organizationNumber__c = orgNumber,
                phone = phone,
                recordTypeId = recordTypeId,
                BillingCity = 'Pocatello',
                BillingCountry = 'USA',
                BillingPostalCode = '83204',
                BillingState = 'ID',
                BillingStreet = '123 Main Street'
            );
            accts.add(a);
        }
        if (doInsert) {
            insert accts;
        }
        return accts;
    }

    public static List<Account> createAccountsWithContacts(Integer numAccounts, Integer numContactsPerAcct, Boolean isDnaAccountContact) {
        Integer numContacts = numAccounts * numContactsPerAcct;
        List<Contact> contacts = TestDataFactory.createContacts(numContacts, isDnaAccountContact, false);
        List<Account> accts = TestDataFactory.createAccounts(numAccounts, isDnaAccountContact, false);

        // If there is only one DNA contact per account, treat them as "person accounts".
        if (numContactsPerAcct == 1 && isDnaAccountContact) {
            for (Integer i = 0; i < numAccounts; i++) {
                Account a = accts[i];
                Contact c = contacts[i];
                a.name = 'P' + c.personNumber__c;
                a.memberNumber__c = c.memberNumber__c;
                a.org_number__c = null;
                a.personNumber__c = c.personNumber__c;
                a.phone = c.phone;
            }
        }
        insert accts;

        // Link the contacts to an account
        for (Integer i = 0; i < numContacts; i++) {
            Integer accountIndex = i / numContacts;
            contacts[i].accountId = accts[accountIndex].id;
        }
        insert contacts;

        return accts;
    }

    public static List<Account> createAccountsWithOpps(Integer numAccounts, Integer numOppsPerAcct, Boolean isDnaAccount, String oppRecordTypeName, String stageName) {
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(oppRecordTypeName).getRecordTypeId();

        // Create the accounts and contacts to link to the opportunity.
        List<Account> accts = createAccounts(numAccounts, isDnaAccount, true);

        // Create the opportunities with and link them to the accounts.
        List<Opportunity> opps = new List<Opportunity>();
        for (Account a : accts) {
            List<Opportunity> acctOpps = TestDataFactory.createOpportunities(numOppsPerAcct, recordTypeId, oppRecordTypeName, stageName, a, false);
            opps.addAll(acctOpps);
        }
        insert opps;
        return accts;
    }

    public static Contact createContact(Boolean isDna, Boolean doInsert) {
        List<Contact> contacts = TestDataFactory.createContacts(1, true, doInsert);
        return contacts[0];
    }

    public static List<Contact> createContacts(Integer numContacts, Boolean isDna, Boolean doInsert) {
        String recordTypeName = isDna ? RecordTypeConstants.CONTACT_DNA : RecordTypeConstants.CONTACT_DEFAULT;
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
        Date now = Date.today();
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 0; i < numContacts; i++) {
            String memberNumber = '' + 100 + i;
            String personNumber = '' + 1000 + i;
            String taxId = '666-18-' + String.valueOf(i).leftPad(4, '0');
            String phone = '(123) 123-' + String.valueOf(i).leftPad(4, '0');
            String mailingStreet = i + ' Main Street';
            String idNumber = 'PA1111' + String.valueOf(i).leftPad(4, '0');
            Date idIssueDate = now.addDays(-90);
            Date idExpireDate = idIssueDate.addYears(8);
            Contact c = new Contact(
                Birthdate = Date.newInstance(1976, 8, Math.mod(i, 30)),
                Email = 'test' + i + '@iccu.com',
                FirstName = 'Test' + i,
                LastName = 'Contact',
                MemberNumber__c = memberNumber,
                PersonNumber__c = personNumber,
                Phone = phone,
                RecordTypeId = recordTypeId,
                TaxID__c = taxId,
                IdentificationType__c = '1',
                IdentificationExpirationDate__c = idExpireDate,
                IdentificationIssueDate__c = idIssueDate,
                IdentificationIssueState__c = 'ID',
                IdentificationNumber__c = idNumber,
                MailingStreet = mailingStreet,
                MailingCity = 'Pocatello',
                MailingCountry = 'USA',
                MailingPostalCode = '83204',
                MailingState = 'ID'
            );
            contacts.add(c);
        }
        if (doInsert) {
            insert contacts;
        }
        return contacts;
    }

    public static List<Contact> createContactsWithAccounts(Integer numAccounts, Integer numContactsPerAcct, Boolean isDnaAccountContact, Boolean doInsert) {
        Integer numContacts = numAccounts * numContactsPerAcct;
        List<Contact> contacts = TestDataFactory.createContacts(numContacts, isDnaAccountContact, false);
        List<Account> accts = TestDataFactory.createAccounts(numAccounts, isDnaAccountContact, false);

        // If there is only one DNA contact per account, create the Accounts as "person accounts".
        if (numContactsPerAcct == 1 && isDnaAccountContact) {
            for (Integer i = 0; i < numAccounts; i++) {
                Account a = accts[i];
                Contact c = contacts[i];
                a.name = 'P' + c.personNumber__c;
                a.memberNumber__c = c.memberNumber__c;
                a.personNumber__c = c.personNumber__c;
            }
        }
        insert accts;

        // Link each contact to an account.
        for (Integer i = 0; i < numContacts; i++) {
            Integer accountIndex = i / numContacts;
            contacts[i].accountId = accts[accountIndex].id;
        }
        if (doInsert) {
            insert contacts;
        }

        return contacts;
    }

    public static Case createCase(Id caseRecordTypeId, Id contactId, Id accountId, String status, Boolean doInsert) {
        List<Case> cases = createCases(1, caseRecordTypeId, contactId, accountId, status, doInsert);
        return cases[0];
    }

    public static List<Case> createCases(Integer numCases, Id caseRecordTypeId, Id contactId, Id accountId, String status, Boolean doInsert) {
        List<Case> cases = new List<Case>();
        for (Integer i = 0; i < numCases; i++) {
            Case k = new Case(
                AccountId = accountId,
                ContactId = contactId,
                Description = 'Test Case',
                Priority = 'High',
                Status = status
            );
            cases.add(k);
        }
        if (doInsert) {
            insert cases;
        }

        return cases;
    }

    public static MemberInsight__c createMemberInsight(Id contactId, Boolean doInsert) {
        MemberInsight__c insight = new MemberInsight__c(
            Name = 'Test Insight',
            ExtraDetails__c = 'some extra details',
            InsightType__c = 'Medical',
            ContactID__c = contactId
        );
        if (doInsert) {
            insert insight;
        }

        return insight;
    }

    public static Opportunity createOpportunity(Id recordTypeId, String oppRecordTypeName, String stageName, Account a, Boolean doInsert) {
        List<Opportunity> opps = createOpportunities(1, recordTypeId, oppRecordTypeName, stageName, a, doInsert);
        return opps[0];
    }

    public static List<Opportunity> createOpportunities(Integer numOpps, Id recordTypeId, String oppRecordTypeName, String stageName, Account a, Boolean doInsert) {
        // Determine appropriate values based on record type.
        String oppType = oppRecordTypeName == RecordTypeConstants.OPPORTUNITY_DEPOSIT_PRODUCT ? 'Deposits' : 'Loan';
        String productName = oppRecordTypeName == RecordTypeConstants.OPPORTUNITY_DEPOSIT_PRODUCT ? 'Share Savings' : 'Fixed-Rate Platinum Visa';

        List<Opportunity> opps = new List<Opportunity>();
        for (Integer i = 0; i < numOpps; i++) {
            Opportunity o = new Opportunity(
                accountId = a.id,
                closeDate = System.today().addMonths(1),
                name = a.name + ' - ' + productName + ' #' + i,
                recordTypeId = recordTypeId,
                product__c = productName,
                stageName = stageName,
                type = oppType
            );
            opps.add(o);
        }
        if (doInsert) {
            insert opps;
        }

        return opps;
    }

    public static List<Opportunity> createOppsWithAccounts(
        Integer numAccounts,
        Integer numOppsPerAcct,
        String oppRecordTypeName,
        String stageName,
        Boolean isDnaAccount,
        Boolean doInsert)
    {
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(oppRecordTypeName).getRecordTypeId();

        // Create the accounts to link to the opportunity.
        List<Account> accts = TestDataFactory.createAccounts(numAccounts, isDnaAccount, true);

        // Create the opportunities and link them to the accounts.
        List<Opportunity> opps = new List<Opportunity>();
        for (Account a : accts) {
            List<Opportunity> acctOpps = TestDataFactory.createOpportunities(numOppsPerAcct, recordTypeId, oppRecordTypeName, stageName, a, false);
            opps.addAll(acctOpps);
        }
        if (doInsert) {
            insert opps;
        }
        return opps;
    }

    public static List<Opportunity> createOppsWithAccountsContactsAndPrimaryRole(
        Integer numAccounts,
        Integer numOppsPerAcct,
        String oppRecordTypeName,
        String stageName,
        Boolean isDnaAccount)
    {
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(oppRecordTypeName).getRecordTypeId();

        // Create the accounts to link to the opportunity.
        List<Account> accts = TestDataFactory.createAccounts(numAccounts, isDnaAccount, true);

        // Create the contacts
        List<Contact> contacts = TestDataFactory.createContacts(numAccounts, isDnaAccount, false);
        for (Integer i = 0; i < numAccounts; i++) {
            contacts[i].accountId = accts[i].id;
        }
        insert contacts;

        // Create the opportunities and link them to the accounts.
        List<Opportunity> opps = new List<Opportunity>();
        for (Account a : accts) {
            List<Opportunity> acctOpps = createOpportunities(numOppsPerAcct, recordTypeId, oppRecordTypeName, stageName, a, false);
            opps.addAll(acctOpps);
        }
        insert opps;

        // Create the primary opportunity contact role.
        List<OpportunityContactRole> oppContactRoles = new List<OpportunityContactRole>();
        for (Integer i = 0; i < numAccounts; i++) {
            for (Integer j = 0; j < numOppsPerAcct; j++) {
                OpportunityContactRole r = new OpportunityContactRole();
                r.ContactId = contacts[i].id;
                r.OpportunityId = opps[(i * numOppsPerAcct) + j].id;
                r.role = AOConstants.OPPORTUNITY_ROLE_PRIMARY_BORROWER;
                r.IsPrimary = true;
                oppContactRoles.add(r);
            }
        }
        insert oppContactRoles;

        return opps;
    }

    public static List<Opportunity> createOppsWithPrimaryRoles(Integer numOpps, Id recordTypeId, String oppRecordTypeName, String stageName, Account a, Contact c) {
        List<Opportunity> opps = TestDataFactory.createOpportunities(numOpps, recordTypeId, oppRecordTypeName, stageName, a, true);

        List<OpportunityContactRole> oppContactRoles = new List<OpportunityContactRole>();
        for (Opportunity o : opps) {
            OpportunityContactRole r = new OpportunityContactRole();
            r.ContactId = c.id;
            r.OpportunityId = o.id;
            r.role = AOConstants.OPPORTUNITY_ROLE_PRIMARY_BORROWER;
            r.IsPrimary = true;
            oppContactRoles.add(r);
        }
        insert oppContactRoles;

        return opps;
    }

    public static List<Lead> createLeads(Integer numLeads, Boolean doInsert) {
        List<Lead> leads = new List<Lead>();
        for(Integer i = 0; i < numLeads; i++) {
            Lead l = new Lead(
                company='Lead Company ' + i,
                email='lead' + i + '@unknown.domain.com',
                firstName='Test' + i,
                lastName='Lead'
            );
            leads.add(l);
        }
        if (doInsert) {
            insert leads;
        }
        return leads;
    }

    public static User createUser(String roleName, String profileName, List<String> permissionSetNames) {
        // Determine the role to assign to the user.
        List<UserRole> roles = [
            SELECT Id
            FROM UserRole
            WHERE Name = :roleName
        ];
        Id roleId = roles[0].id;

        // Determine the profile to assign to the user.
        List<Profile> profiles = [
            SELECT Id
            FROM Profile
            WHERE Name = :profileName
        ];
        Id profileId = profiles[0].id;

        // Create the user.
        User u = new User(
            alias='testuser',
            cashBox__c = '9999',
            email='testuser@iccu.com.invalid',
            emailEncodingKey='ISO-8859-1',
            extension='9999',
            firstName='Test',
            isActive=true,
            lastName='User',
            languageLocaleKey='en_US',
            localeSidKey='en_US',
            networkNodeName__c = 'SomeNetworkNode',
            profileId=profileId,
            timeZoneSidKey='America/Denver',
            title='Test Title',
            username='testuser@iccu.com'
        );
        insert u;

        // Assign permission sets.
        if (permissionSetNames != null && permissionSetNames.size() > 0) {
            List<PermissionSet> permissionSets = [
                SELECT Id
                FROM PermissionSet
                WHERE Name IN :permissionSetNames
            ];
            List<PermissionSetAssignment> assignments = new List<PermissionSetAssignment>();
            for (PermissionSet ps : permissionSets) {
                PermissionSetAssignment a = new PermissionSetAssignment(AssigneeId = u.id, PermissionSetId = ps.id);
                assignments.add(a);
            }
            insert assignments;
        }

        return u;
    }

}