objects/Case.object
<CustomObject>
    <fields>
        <fullName>MCCClass__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Specific</fullName>
                </value>
                <value>
                    <fullName>Branch Services</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Business Contact Maintenance</fullName>
                </value>
                <value>
                    <fullName>Business eBranch</fullName>
                </value>
                <value>
                    <fullName>Check Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Debit / Credit Card</fullName>
                </value>
                <value>
                    <fullName>Deposit Products</fullName>
                </value>
                <value>
                    <fullName>Dropped Call</fullName>
                </value>
                <value>
                    <fullName>eBranch</fullName>
                </value>
                <value>
                    <fullName>Electronic Services</fullName>
                </value>
                <value>
                    <fullName>Fees</fullName>
                </value>
                <value>
                    <fullName>Hours of Operation</fullName>
                </value>
                <value>
                    <fullName>IRA</fullName>
                </value>
                <value>
                    <fullName>Locations</fullName>
                </value>
                <value>
                    <fullName>Membership Requirements</fullName>
                </value>
                <value>
                    <fullName>Merchant Services</fullName>
                </value>
                <value>
                    <fullName>Mortgage Loan Products</fullName>
                </value>
                <value>
                    <fullName>NPS Follow Up</fullName>
                </value>
                <value>
                    <fullName>Payments</fullName>
                </value>
                <value>
                    <fullName>Personal Maintenance</fullName>
                </value>
                <value>
                    <fullName>Phone Call Transfer</fullName>
                </value>
                <value>
                    <fullName>Promotions</fullName>
                </value>
                <value>
                    <fullName>Special Event</fullName>
                </value>
                <value>
                    <fullName>Tax Questions</fullName>
                </value>
                <value>
                    <fullName>Touch Tone Teller (TTT)</fullName>
                </value>
                <value>
                    <fullName>Wrong Department</fullName>
                </value>
                <value>
                    <fullName>Business Questions</fullName>
                    <isActive>false</isActive>
                    <label>Business Questions</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MCCSubclass__c</fullName>
        <description>All possible subclasses</description>
        <label>Subclass</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MCCClass__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1098</fullName>
                </value>
                <value>
                    <fullName>1099</fullName>
                </value>
                <value>
                    <fullName>Account/Routing Number</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>Account Closure</fullName>
                </value>
                <value>
                    <fullName>Account Holds</fullName>
                </value>
                <value>
                    <fullName>Accounting</fullName>
                </value>
                <value>
                    <fullName>Account Locks</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Names</fullName>
                </value>
                <value>
                    <fullName>Add/Remove Account</fullName>
                </value>
                <value>
                    <fullName>Add Joint</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Adjustments</fullName>
                </value>
                <value>
                    <fullName>Authorized Signers</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Auto Refinance</fullName>
                </value>
                <value>
                    <fullName>AVP</fullName>
                </value>
                <value>
                    <fullName>Beneficial Ownership</fullName>
                </value>
                <value>
                    <fullName>Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch</fullName>
                </value>
                <value>
                    <fullName>Branch Performance</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Business Development &amp; Public Relations</fullName>
                </value>
                <value>
                    <fullName>Business Lending</fullName>
                </value>
                <value>
                    <fullName>Business Membership Requirements</fullName>
                </value>
                <value>
                    <fullName>Business Relationship</fullName>
                </value>
                <value>
                    <fullName>Business Underwriting</fullName>
                </value>
                <value>
                    <fullName>Card Activation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MemberSentiment__c</fullName>
        <label>Member Sentiment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <label>1 - very unsatisfied</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 - unsatisfied</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 - neutral</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 - satisfied</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 - very satisfied</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

classes/MemberCasesController.cls
public class MemberCasesController {
    private static Integer DEFAULT_DAYS_AGO = 90;

    @AuraEnabled
    public static List<Case> getOpenAccountCases(Id accountId) {
        if (accountId == null) {
            throw new IllegalArgumentException('The `accountId` cannot be null.');
        }

        Case[] cases = [
            SELECT
                CaseNumber,
                CreatedDate,
                ClosedDate,
                Description,
                OwnerId,
                Priority,
                Status,
                Subject,
                MCCClass__c,
                MCCSubclass__c,
                MemberSentiment__c,
                Owner.Name,
                RecordTypeId
            FROM Case
            WHERE
                AccountId = :accountId AND
                IsClosed = false
            ORDER BY
                CreatedDate DESC
        ];

        return cases;
    }

    @AuraEnabled
    public static List<Case> getOpenMemberCases(Id contactId) {
        if (contactId == null) {
            throw new IllegalArgumentException('The `contactId` cannot be null.');
        }

        Case[] cases = [
            SELECT
                CaseNumber,
                CreatedDate,
                ClosedDate,
                Description,
                OwnerId,
                Priority,
                Status,
                Subject,
                MCCClass__c,
                MCCSubclass__c,
                MemberSentiment__c,
                Owner.Name,
                RecordTypeId
            FROM Case
            WHERE
                ContactId = :contactId AND
                isClosed = false
            ORDER BY
                CreatedDate DESC
        ];

        return cases;
    }

    public static List<Case> getClosedMemberCases(Id contactId) {
        return getClosedMemberCases(contactId, DEFAULT_DAYS_AGO);
    }

    @AuraEnabled
    public static List<Case> getClosedMemberCases(Id contactId, Integer numberOfDaysAgo) {
        if (contactId == null) {
            throw new IllegalArgumentException('The `contactId` cannot be null.');
        }

        // Fun Aura bug I found.  APEX doessn't correctly deserialize Integers, so we have to reparse the integer.
        // https://blog.texei.com/lightning-components-auraenabled-method-parameters-whats-working-and-what-s-not-83c351356104
        numberOfDaysAgo = Integer.valueOf(numberOfDaysAgo);

        if (numberOfDaysAgo == null || numberOfDaysAgo <= 0) {
            numberOfDaysAgo = DEFAULT_DAYS_AGO;
        }

        DateTime daysAgo = System.now().addDays(-numberOfDaysAgo);

        Case[] cases = [
            SELECT
                CaseNumber,
                CreatedDate,
                ClosedDate,
                Description,
                OwnerId,
                Priority,
                Status,
                Subject,
                MCCClass__c,
                MCCSubclass__c,
                MemberSentiment__c,
                Owner.Name,
                RecordTypeId
            FROM Case
            WHERE
                ContactId = :contactId AND
                isClosed = true AND
                ClosedDate >= :daysAgo
            ORDER BY
                CreatedDate DESC
        ];

        return cases;
    }

    /**
     * This function is necessary because an aura component may only specify one controller.  This is an accessor
     * method that should be removed once the aura component(s) are migrated to LWC.
     */
    @AuraEnabled
    public static Map<String, Object> getContactOpportunities(Id contactId) {
        return ContactOpportunityController.getContactOpportunities(contactId);
    }
}