objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BusinessPhone__c</fullName>
        <description>Customers phone number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IdentificationExpirationDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueState__c</fullName>
        <label>Identification Issue State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IdentificationNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IdentificationType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Type</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Member Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PersonNumber__c</fullName>
        <description>Number provided by DNA</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Person Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TaxID__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AOApplicantRestResponse.cls
global with sharing class AOApplicantRestResponse {
    global List<String> error_messages;
    global AOApplicationRestRequest.Person applicant;

    global AOApplicantRestResponse(List<String> errorMessages, Contact c) {
        error_messages = errorMessages;

        applicant = new AOApplicationRestRequest.Person();
        if (c != null) {
            applicant.person_number = c.personNumber__c;
            applicant.member_number = c.memberNumber__c;
            applicant.tax_id = c.taxId__c;
            applicant.first_name = c.firstName;
            applicant.last_name = c.lastName;
            applicant.birth_date = formatDate(c.birthDate);
            applicant.home_phone = new AOApplicationRestRequest.Phone();
            applicant.home_phone.phone_number = c.phone;
            applicant.mobile_phone = new AOApplicationRestRequest.Phone();
            applicant.mobile_phone.phone_number = c.mobilePhone;
            applicant.work_phone = new AOApplicationRestRequest.Phone();
            applicant.work_phone.phone_number = c.businessPhone__c;
            applicant.email = c.email;

            // Provide the identification information on file.
            applicant.identification = new AOApplicationRestRequest.PersonIdentification();
            applicant.identification.type = c.identificationType__c;
            applicant.identification.id_number = c.identificationNumber__c;
            applicant.identification.issuing_authority = c.identificationIssueState__c;
            applicant.identification.issue_date = formatDate(c.identificationIssueDate__c);
            applicant.identification.expire_date = formatDate(c.identificationExpirationDate__c);

            // Provide the mailing address on file.
            List<String> addressLines = c.mailingStreet != null ? c.mailingStreet.split('\\r?\\n') : new List<String>();
            applicant.primary_address = new AOApplicationRestRequest.Address();
            applicant.primary_address.line_1 = addressLines.size() > 0 ? addressLines[0] : null;
            applicant.primary_address.line_2 = addressLines.size() > 1 ? addressLines[1] : null;
            applicant.primary_address.city = c.mailingCity;
            applicant.primary_address.state = c.mailingState;
            applicant.primary_address.postal_code = c.mailingPostalCode;
            applicant.primary_address.country = c.mailingCountry;
        }
    }

    @TestVisible
    private String formatDate(Date d) {
        String formatted = d != null ? DateUtils.format(d, 'yyyy-MM-dd') : null;
        return formatted;
    }
}