objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BusinessPhone__c</fullName>
        <description>Customers phone number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IdentificationExpirationDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueState__c</fullName>
        <label>Identification Issue State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IdentificationNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IdentificationType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Type</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Member Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PersonNumber__c</fullName>
        <description>Number provided by DNA</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Person Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TaxID__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AOApplicantRestService.cls
@RestResource(urlMapping='/accountopening/applicant/*')
global with sharing class AOApplicantRestService {

    /**
     * Search for the applicant by tax Id.
     */
    @HttpGet
    global static AOApplicantRestResponse search() {
        AOApplicationRestRequest request = AORestHelper.parseRequestBody();

        RestResponse res = RestContext.response;
        List<String> errorMessages = new List<String>();
        Contact c = null;
        try {
            Id dnaRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(RecordTypeConstants.CONTACT_DNA).getRecordTypeId();
            c = AOApplicantRestService.lookupContact(request.applicant.person.tax_id, dnaRecordTypeId, false);
            if (c == null) {
                errorMessages.add('The applicant was not found.');
            }
            res.statusCode = 200;
        } catch (Exception e) {
            errorMessages.add('The lookup of the applicant failed.  ' + e.getMessage());
            res.statusCode = 500;
        }

        AOApplicantRestResponse response = new AOApplicantRestResponse(errorMessages, c);
        return response;
    }

    @HttpPost
    global static AOApplicantRestResponse createApplicant() {
        RestResponse res = RestContext.response;
        res.statusCode = 405;
        List<String> errorMessages = new List<String> {'The createApplicant method is for future use and is not yet implemented.'};
        AOApplicantRestResponse response = new AOApplicantRestResponse(errorMessages, null);
        return response;
    }

    @HttpPut
    global static AOApplicantRestResponse updateApplicant() {
        RestResponse res = RestContext.response;
        res.statusCode = 405;
        List<String> errorMessages = new List<String> {'The updateApplicant method is for future use and is not yet implemented.'};
        AOApplicantRestResponse response = new AOApplicantRestResponse(errorMessages, null);
        return response;
    }

    private static Contact lookupContact(String taxId, Id recordTypeId, Boolean lock) {
        if (String.isBlank(taxId)) {
            throw new IllegalArgumentException('The taxId must be provided.');
        }
        String sqlStatement =
            'SELECT id, birthDate, businessPhone__c, email, firstName, lastName, memberNumber__c, mobilePhone, personNumber__c, phone, identificationType__c, identificationNumber__c, identificationIssueState__c, identificationIssueDate__c, identificationExpirationDate__c, mailingStreet, mailingCity, mailingState, mailingPostalCode, mailingCountry, taxId__c ' +
            'FROM Contact ' +
            'WHERE taxId__c = :taxId ' +
            (recordTypeId != null ? 'AND recordTypeId = :recordTypeId ' : '') +
            'ORDER BY createdDate ASC ' +
            (lock ? 'FOR UPDATE' : '');
        List<Contact> contacts = (List<Contact>)Database.query(sqlStatement);
        Contact c = contacts.size() > 0 ? contacts[0] : null;
        return c;
    }

}