objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BusinessPhone__c</fullName>
        <description>Customers phone number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>IdentificationExpirationDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Issue Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IdentificationIssueState__c</fullName>
        <label>Identification Issue State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AA</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IdentificationNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Identification Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IdentificationType__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Type</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MemberNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Member Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PersonNumber__c</fullName>
        <description>Number provided by DNA</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Person Number</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TaxID__c</fullName>
        <encryptionScheme>CaseSensitiveDeterministicEncryption</encryptionScheme>
        <label>Tax ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AOApplicantRestServiceTest.cls
@IsTest
private without sharing class AOApplicantRestServiceTest {

    @IsTest
    private static void testGetApplicant() {
        List<Contact> contacts = TestDataFactory.createContactsWithAccounts(1, 1, true, true);
        Contact c = contacts[0];

        // A minimalistic request with a lot of null/empty nodes to validate that the system
        // handles this gracefully.
        RestRequest request = new RestRequest();
        request.requestUri = 'https://test.salesforce.com/services/apexrest/accountopening/applicant';
        request.httpMethod = 'GET';
        request.requestBody = Blob.valueOf('{"applicant":{"person":{"tax_id":"' + c.taxId__c + '"}}}');
        RestContext.request = request;
        RestContext.response = new RestResponse();

        Test.startTest();

        AOApplicantRestResponse response = AOApplicantRestService.search();

        Test.stopTest();

        // Verify the HTTP status code.
        System.assertEquals(200, RestContext.response.statusCode);

        // Verify the response is properly formatted.
        System.assertNotEquals(null, response);
        System.assertNotEquals(null, response.error_messages);
        System.assertEquals(0, response.error_messages.size());
        System.assertEquals(c.PersonNumber__c, response.applicant.person_number);
        System.assertEquals(c.MemberNumber__c, response.applicant.member_number);
        System.assertEquals(c.TaxID__c, response.applicant.tax_id);
        System.assertEquals(c.FirstName, response.applicant.first_name);
        System.assertEquals(c.LastName, response.applicant.last_name);
        System.assertEquals(response.formatDate(c.Birthdate), response.applicant.birth_date);
        System.assertEquals(c.Phone, response.applicant.home_phone.phone_number);
        System.assertEquals(c.MobilePhone, response.applicant.mobile_phone.phone_number);
        System.assertEquals(c.BusinessPhone__c, response.applicant.work_phone.phone_number);
        System.assertEquals(c.Email, response.applicant.email);
        System.assertEquals(c.MailingStreet, response.applicant.primary_address.line_1);
        System.assertEquals(c.MailingCity, response.applicant.primary_address.city);
        System.assertEquals(c.MailingCountry, response.applicant.primary_address.country);
        System.assertEquals(c.MailingPostalCode, response.applicant.primary_address.postal_code);
        System.assertEquals(c.MailingState, response.applicant.primary_address.state);
        System.assertEquals(c.IdentificationType__c, response.applicant.identification.type);
        System.assertEquals(c.IdentificationNumber__c, response.applicant.identification.id_number);
        System.assertEquals(c.IdentificationIssueState__c, response.applicant.identification.issuing_authority);
        System.assertEquals(response.formatDate(c.IdentificationIssueDate__c), response.applicant.identification.issue_date);
        System.assertEquals(response.formatDate(c.IdentificationExpirationDate__c), response.applicant.identification.expire_date);
    }

    @IsTest
    private static void testApplicantNotFound() {
        // A minimalistic request with a lot of null/empty nodes to validate that the system
        // handles this gracefully.
        RestRequest request = new RestRequest();
        request.requestUri = 'https://test.salesforce.com/services/apexrest/accountopening/applicant';
        request.httpMethod = 'GET';
        request.requestBody = Blob.valueOf('{"applicant":{"person":{"tax_id":"555-11-1111"}}}');
        RestContext.request = request;
        RestContext.response = new RestResponse();

        Test.startTest();

        AOApplicantRestResponse response = AOApplicantRestService.search();

        Test.stopTest();

        // Verify the HTTP status code.
        System.assertEquals(200, RestContext.response.statusCode);

        // Verify the response is properly formatted.
        System.assertNotEquals(null, response);
        System.assertNotEquals(null, response.error_messages);
        System.assertEquals(1, response.error_messages.size());
        System.assertEquals('The applicant was not found.', response.error_messages[0]);
    }

    @IsTest
    private static void testPostApplicant() {
        RestRequest request = new RestRequest();
        request.requestUri = 'https://test.salesforce.com/services/apexrest/accountopening/applicant';
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{}');
        RestContext.request = request;
        RestContext.response = new RestResponse();

        Test.startTest();

        AOApplicantRestResponse response = AOApplicantRestService.createApplicant();

        Test.stopTest();

        // Verify the HTTP status code.
        System.assertEquals(405, RestContext.response.statusCode);

        // Verify the response is properly formatted.
        System.assertNotEquals(null, response);
        System.assertNotEquals(null, response.error_messages);
        System.assertEquals(1, response.error_messages.size());
        System.assertEquals('The createApplicant method is for future use and is not yet implemented.', response.error_messages[0]);
    }

    @IsTest
    private static void testPutApplicant() {
        RestRequest request = new RestRequest();
        request.requestUri = 'https://test.salesforce.com/services/apexrest/accountopening/applicant';
        request.httpMethod = 'PUT';
        request.requestBody = Blob.valueOf('{}');
        RestContext.request = request;
        RestContext.response = new RestResponse();

        Test.startTest();

        AOApplicantRestResponse response = AOApplicantRestService.updateApplicant();

        Test.stopTest();

        // Verify the HTTP status code.
        System.assertEquals(405, RestContext.response.statusCode);

        // Verify the response is properly formatted.
        System.assertNotEquals(null, response);
        System.assertNotEquals(null, response.error_messages);
        System.assertEquals(1, response.error_messages.size());
        System.assertEquals('The updateApplicant method is for future use and is not yet implemented.', response.error_messages[0]);
    }

}