objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CreditScore__c</fullName>
        <inlineHelpText>FICO</inlineHelpText>
        <label>Credit Score</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>DNA</fullName>
        <active>true</active>
        <description>Imported from DNA</description>
        <label>DNA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/MarketingPromotion__c.object
<CustomObject>
    <description>An object that models a marketing promotion to be offered to the member.</description>
    <fields>
        <fullName>ColorPicker__c</fullName>
        <label>Icon Color</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>red</fullName>
                </value>
                <value>
                    <fullName>green</fullName>
                </value>
                <value>
                    <fullName>blue</fullName>
                </value>
                <value>
                    <fullName>purple</fullName>
                </value>
                <value>
                    <fullName>darkBlue</fullName>
                    <isActive>false</isActive>
                    <label>darkBlue</label>
                </value>
                <value>
                    <fullName>darkGrey</fullName>
                    <isActive>false</isActive>
                    <label>darkGrey</label>
                </value>
                <value>
                    <fullName>yellow</fullName>
                    <isActive>false</isActive>
                    <label>yellow</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>The end date for which the promotion is effective.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaximumCreditScore__c</fullName>
        <description>The maximum credit score a person can have to qualify for this product.</description>
        <inlineHelpText>The maximum credit score a person can have to qualify for this product.</inlineHelpText>
        <label>MaximumCreditScore</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MinimumCreditScore__c</fullName>
        <description>The minimum credit score needed to qualify for this product.</description>
        <inlineHelpText>The minimum credit score needed to qualify for this product.</inlineHelpText>
        <label>MinimumCreditScore</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>The start date for which the promotion is effective.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Marketing Promotion</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Marketing Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Marketing Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ProductOfferingsController.cls
public class ProductOfferingsController {
    @TestVisible
    private static INetworkFactory networkFactory;

    @AuraEnabled
    public static Map<String, Object> getProductOfferings(String contactId) {
        if (ProductOfferingsController.networkFactory == null) {
            ProductOfferingsController.networkFactory = new ConcreteNetworkProvider();
        }

        if (contactId == null) {
            Map<String, Object> response = new Map<String, Object>();
            response.put('error', 'There was a problem getting contacts. Contact ID was null.');

            return response;
        }

        INetworkFactory networkFactory = ProductOfferingsController.networkFactory;
        IProductOfferingDataProvider offeringDataProvider = networkFactory.getProductOfferingDataProvider();

        try {
            SFPerson person = SFPerson.getInstance(contactId);
            List<ProductOfferingGroup> groups = offeringDataProvider.getProductOfferings(person);

            List<Map<String, Object>> mappedGroups = new List<Map<String, Object>>();

            for (ProductOfferingGroup offeringGroup : groups) {
                List<Map<String, Object>> mappedOfferings = new List<Map<String, Object>>();

                for (ProductOffering offering : offeringGroup.getOfferings()) {
                    Map<String, Object> mappedOffering = new Map<String, Object>();
                    mappedOffering.put('title', offering.getTitle());
                    mappedOffering.put('agentScript', offering.getAgentScript());
                    mappedOffering.put('icon', offering.getIconName());
                    mappedOffering.put('color', offering.getColor());
                    mappedOffering.put('weight', offering.getWeight());

                    mappedOfferings.add(mappedOffering);
                }

                Map<String, Object> mappedGroup = new Map<String, Object>();
                mappedGroup.put('title', offeringGroup.getTitle());
                mappedGroup.put('offerings', mappedOfferings);

                mappedGroups.add(mappedGroup);
            }

            Map<String, Object> response = new Map<String, Object>();
            response.put('offeringGroups', mappedGroups);
            response.put('error', null);

            return response;
        } catch (UnauthenticatedException e) {
            Map<String, Object> response = new Map<String, Object>();
            response.put('offeringGroups', null);
            response.put('error', 'Please log into DNA.');

            return response;
        } catch (Exception e) {
            Map<String, Object> response = new Map<String, Object>();
            response.put('offeringGroups', null);
            response.put('error', 'There was a problem getting product offerings. Please try again later. ' + String.valueOf(e));

            return response;
        }
    }

    @AuraEnabled
    public static List<MarketingPromotion__c> getMarketingPromotions(String contactId) {
        // Retrieve the contacts credit score.
        Contact contact = SFPerson.getInstance(contactId).getContact();
        Integer creditScore = 0;
        if (contact.CreditScore__c != null) {
            creditScore = (Integer)contact.CreditScore__c;
        }

        Date today = Date.today();
        MarketingPromotion__c[] promotions = [
            SELECT
                ColorPicker__c,
                EndDate__c,
                Name,
                StartDate__c
            FROM MarketingPromotion__c
            WHERE
                StartDate__c <= :today AND
                EndDate__c >= :today AND
                MinimumCreditScore__c <= :creditScore AND
                MaximumCreditScore__c >= :creditScore
            ORDER BY EndDate__c ASC
        ];

        return promotions;
    }
}