objects/ServiceAccounts__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>APIClientId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>APIClientId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>APIClientSecret__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>APIClientSecret</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ServiceName</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ServiceAccounts</label>
</CustomObject>

classes/ESignProviderFactory.cls
public class ESignProviderFactory {
    public static IESignProvider getESignProvider() {
        ServiceAccounts__c mulesoftESign = [
            SELECT
                APIClientID__c,
                APIClientSecret__c
            FROM ServiceAccounts__c
            WHERE ServiceName__c = 'MuleSoftESign'
            LIMIT 1
        ];

        EndpointManager mgr = new EndpointManager();

        String endpoint = mgr.getESignEndpoint();
        String clientId = mulesoftESign.APIClientID__c;
        String clientSecret = mulesoftESign.APIClientSecret__c;

        return new MuleSoftESignProvider(endpoint, clientId, clientSecret);
    }
}